services:
  composer:
    image: composer:latest
    volumes:
      - .:/app

  tests:
    image: php:8.1-cli
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: vendor/bin/phpunit

  coverage:
    build: ./docker/coverage/
    environment:
      - XDEBUG_MODE=coverage
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: vendor/bin/phpunit --coverage-html var/coverage
